### PR TITLE
Title field

### PR DESCRIPTION
**Pull request by leogilmour**
unintended consequences of removing title field, exchanging for venue field

### CODE REVIEW

**Comment by leonoragilmour** [comment]
@libuk  This ok?

**Review by ecoad — APPROVED** [review]
I approve of these changes.

**Review by jonsherrard — APPROVED** [review]
Tag and update croissant heavy.

Create a `hotfix/v4.0.1` branch that PRs into `v4.x`

**Review by libuk — APPROVED** [review]
Sweet

**Pull request merged**
